const WelcomeText = [
    "Dúfam, že dnes budeš mať krásny a úsmevný deň! 😊",
    "Nech je tvoj deň plný radosti a pekných prekvapení! 💕",
    "Posielam ti objatie na šťastný deň! 🤗",
    "Usmievaj sa, pretože dnes je krásny deň! ☀️",
    "Nech ťa dnes sprevádza len šťastie a láska. 💖",
    "Užívaj si každý okamih dnešného dňa! ✨",
    "Nech je tvoj deň taký nádherný ako tvoj úsmev! 😘",
    "Posielam ti kopu dobrej nálady na dnešok! 🎈",
    "Dnes si zaslúžiš len radosť a pohodu! 🌸",
    "Verím, že dnešný deň ti prinesie veľa krásnych chvíľ. 🌞",
    "Nech sa ti dnes splní niečo krásne! 🌈",
    "Pošli svetu úsmev a on ti ho vráti. 😊",
    "Tvoj deň bude úžasný – pretože si úžasná! 💕",
    "Dnes je nový deň plný nových možností, uži si ho! ✨",
    "Dúfam, že dnes budeš mať veľa dôvodov na úsmev! 😍",
    "Nezabudni, že si milovaná každý jeden deň. ❤️",
    "Nech ti dnešok prinesie len radosť a šťastie! 🌼",
    "Dnes je ideálny deň na to, aby si bola šťastná! 🌟",
    "Tvoje šťastie je pre mňa najdôležitejšie – maj krásny deň! 💖",
    "Slnečný deň ti praje ten, kto ťa má rád! 🌞",
    "Uži si tento krásny deň naplno! 😘",
    "Nech je každý moment dneška plný krásnych emócií. 🌸",
    "Šťastie je v malých veciach – nájdi ich dnes! 🍀",
    "Verím, že dnes sa ti splní niečo krásne! 🌟",
    "Nech máš dnes veľa dôvodov na úsmev! 😊",
    "Si svetlo môjho života, tak nech je tvoj deň svetlý! 💖",
    "Každý deň je dar – uži si ho naplno! 🎁",
    "Nech ťa dnes obklopuje len láska a pohoda. 💕",
    "Tvoj úsmev robí môj deň krajším – usmievaj sa! 😍",
    "Prajem ti nádherný deň plný dobrej nálady! 🌼",
    "Dnes je deň na nové zážitky – uži si ich! ✨",
    "Verím, že dnešok bude pre teba úžasný! 🌈",
    "Nech máš dnes dostatok lásky, smiechu a radosti! 💖",
    "Tvoj úsmev je to najkrajšie, čo dnes chcem vidieť! 😊",
    "Nech sa ti dnes všetko darí a cítiš sa skvele! 🌸",
    "Dnes je krásny deň, pretože v ňom si ty! 😘",
    "Pošli do sveta dobrú energiu a ona sa ti vráti! ✨",
    "Nech máš dnes deň plný malých zázrakov! 🌼",
    "Ráno začína s úsmevom a tvoj deň bude dokonalý! 😊",
    "Nech je dnešok plný lásky, radosti a krásnych chvíľ! 💕",
    "Si moje slniečko – nech je dnes krásny deň aj pre teba! 🌞",
    "Dnes je ideálny deň na nové dobrodružstvá! 🚀",
    "Nech sa dnes deje len to najlepšie! 🌸",
    "Zaslúžiš si šťastný a úsmevný deň! 💖",
    "Pošli svetu úsmev a on ti ho stokrát vráti! 😊",
    "Uži si dnes všetky krásne momenty naplno! 🌟",
    "Nech je dnešok naplnený len dobrou energiou! 💕",
    "Tvoje šťastie je pre mňa najväčšou radosťou! 😍",
    "Nech je dnešný deň taký výnimočný ako ty! ✨",
    "Maj nádherný deň plný lásky a radosti! ❤️",
    "pup"
  ];
  
  export default WelcomeText;
  